language: ruby
rvm:
  - 2.4.1

script:
    - bundle update --bundler
    - bundle exec jekyll build && bundle exec htmlproofer ./_site

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  skip_cleanup: true
  local_dir: _site
  default_text_charset: 'utf-8'
