name: GitHub CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    name: Ruby 2.7 environment

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Build website
        run: bundle exec jekyll build

      - name: Test website
        run: bundle exec htmlproofer --url-ignore https://www.twitter.com/trellisldp,https://twitter.com/trellisldp ./_site

